### ISSUE TITLE
Switch the Ubuntu base repositories to HTTPS

### ISSUE THREAD

**Issue by wilmardo** [linuxserver/docker-baseimage-xenial#12]
While switching [mono](https://github.com/linuxserver/docker-baseimage-mono/pull/5) and [radarr](https://github.com/linuxserver/docker-radarr/pull/27) to https I noticed the base `lsiobase/xenial-root-x86` has only http:// base repositories. Is this something that could be fixed? 
This also would remove the need to install `apt-https-transport` on each subsequent image using a https repository since at is installed in the root image.

Couldn't find a repo for the root image therefore the issue here :)

**Comment by aptalca** [comment]
ubuntu baseimages are at:
https://github.com/linuxserver/docker-baseimage-ubuntu for bionic and
https://github.com/linuxserver/docker-baseimage-ubuntu/tree/xenial for xenial

**Comment by aptalca** [comment]
With that said, I don't see a benefit to using https for repos.

Closing for now, you can reopen if you would like to discuss further
