### ISSUE TITLE
Docker build hang with lastest lsiobase/ubuntu:bionic

### ISSUE THREAD

**Issue by sinopsysHK** [linuxserver/docker-baseimage-xenial#13]
I've tried to rebuild some linuxserver.io docker image from my synology and they all hang at the end of the first RUN instruction.
I suspect an issue with s6-overlay but I do not know how to trouble shoot.

I have no error message, process remains alive even if not using CPU and it last for ever.

When I try to get into the current building container I get: 
`rpc error: code = 2 desc = containerd: container not found`

While when I do docker ps I still see it as running:
`CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                                                             NAMES`
`e516c8fa1c75        fe9ae0f2be26             "/bin/sh -c 'echo ..."   31 minutes ago      Up 31 minutes                                                                                         dreamy_fermat
`
And once I kill the ongoing building process, docker ps still show me the same zombi container.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by aptalca** [comment]
This is a baseimage, not meant to create containers from.

**Comment by sinopsysHK** [comment]
Sorry I might have been misleading in my explanation.

I'm trying to build my image using lsiobase/ubuntu:bionic as the base image and it is during the docker build process that it hangs at the end of the first RUN instruction.

HostOS: Linux 3.10.105 x86_64  GNU/Linux synology_x86_411+II

Command used:
` docker build -t synopsyshk/docker-kodi-headless .`

RUN instruction that hangs:
`RUN echo "**** install build packages ****" &&  apt-get update &&  apt-get install -y software-properties-common &&  add-apt-repository -s ppa:team-xbmc/xbmc-nightly &&  echo ".... install build packages done ...."`

Build logs:
Step 7/26 : RUN echo "**** install build packages ****" &&  apt-get update &&  apt-get install -y software-properties-common &&  add-apt-repository -s ppa:team-xbmc/xbmc-nightly &&  echo ".... install build packages done ...."; exit 0
 ---> Running in cb20dfeaf28e
**** install build packages ****
Get:1 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
[...]
Processing triggers for dbus (1.12.2-1ubuntu1) ...
 Official Team Kodi nightly builds.
Less stable than unstable, these are untested automated nightly builds.
 More info: https://launchpad.net/~team-xbmc/+archive/ubuntu/xbmc-nightly
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Get:3 http://ppa.launchpad.net/team-xbmc/xbmc-nightly/ubuntu bionic InRelease [15.4 kB]
Hit:4 http://archive.ubuntu.com/ubuntu bionic-security InRelease
Get:5 http://ppa.launchpad.net/team-xbmc/xbmc-nightly/ubuntu bionic/main Sources [30.4 kB]
Get:6 http://ppa.launchpad.net/team-xbmc/xbmc-nightly/ubuntu bionic/main amd64 Packages [34.8 kB]
Fetched 80.6 kB in 4s (20.2 kB/s)
Reading package lists...
.... install build packages done ....

From there nothing more happens despite other RUN instructions after.

Docker logs (docker logs):
`Error response from daemon: configured logging driver does not support reading`


In order to check if it was due to my Dockerfile, I tryied to compile myself a linuxserver.io image: [https://github.com/linuxserver/docker-kodi-headless/tree/Leia](url) -> I have the same behavior with hang right after first RUN instruction processed

**Comment by tobbenb** [comment]
I think aptalca u der stood what you ment. We do not support users trying to build images from our base images.
We don't support anyone building our containers either. 
Seeing as this is an issue you have creating your own container, it's not an issue with our base image.
