### ISSUE TITLE
[BUG] arm32v7 images wrongly tagged

### ISSUE THREAD

**Issue by Olivier6767** [linuxserver/docker-baseimage-xenial#143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In DockerHub, the image `arm32v7-jammy` is wrongly tagged to architecture `linux/amd64`.

When buiklding a container using: `BASE_IMAGE: lsiobase/ubuntu:arm32v7-jammy`
I get the error: `ERROR [MyImge] load metadata for docker.io/lsiobase/ubuntu:arm32v7-jammy `

The same issue exists with `arm32v7-focal`.
Specific version are tagged correctly.

![jammy-arm32](https://github.com/linuxserver/docker-baseimage-ubuntu/assets/28684355/fdd0f846-397c-4911-81de-a1893370a4d3)

### Expected Behavior

This image should be tagged to `linux/arm/v7`

### Steps To Reproduce

Build docker container using
BASE_IMAGE: lsiobase/ubuntu:arm32v7-jammy

### Environment

```markdown
- OS: Ubuntu 22.04
- How docker service was installed: docker-ce
```

### Docker creation

```bash
MyDocker:
    image: myregistry.domain.com/my/MyDocker
    build:
      context: ./MyDocker
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: lsiobase/ubuntu:arm32v7-jammy
```

### Container logs

```bash
ERROR [MyImge] load metadata for docker.io/lsiobase/ubuntu:arm32v7-jammy
```

**Comment by thespad** [comment]
They're not incorrectly tagged https://www.linuxserver.io/blog/a-farewell-to-arm-hf

**Comment by Olivier6767** [comment]
Ok, thanks for the information.
But then the image name should not be named arm32v7... This is confusing.

**Comment by thespad** [comment]
There's no practical way to mass delete all of the 32bit arm manifests for the latest branch tags because registries do not provide viable API routes. Rather than leave users unknowingly using images that would never get updated, we opted to push invalid manifests for the arm32v7-latest (and matching branch) tags to ensure people couldn't pull them by mistake.

All of the older tags remain valid.

**Comment by Olivier6767** [comment]
Ok got it.
Thanks.
