### ISSUE TITLE
[BUG] latest arm32 images have amd64 as arch

### ISSUE THREAD

**Issue by matthuisman** [linuxserver/docker-baseimage-xenial#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/linuxserver/docker-baseimage-ubuntu/assets/6225961/3a906027-ea8c-421e-aa30-3d3ed97b4444)

### Steps To Reproduce

n/a

### Environment

```markdown
- OS:
- How docker service was installed:
```

### Docker creation

```bash
n/a
```

### Container logs

```bash
n/a
```

**Comment by Roxedus** [comment]
We do not offer arm32 builds. https://www.linuxserver.io/blog/a-farewell-to-arm-hf
This tagging is done deliberately to force an error, to not give the impression that the 32 bit tag is truly "latest". All previous tags are untouched.

**Comment by matthuisman** [comment]
perfect. thank you. ill just use the previous tag
