### ISSUE TITLE
[BUG] s6-supervise <process_name>: warning: unable to spawn ./run (waiting 60 seconds): Permission denied

### ISSUE THREAD

**Issue by dgraziotin** [linuxserver/docker-baseimage-xenial#173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I maintain [dgraziotin/docker-nginx-webdav-nononsense](https://github.com/dgraziotin/docker-nginx-webdav-nononsense) that is based on linuxserver/baseimage-ubuntu:jammy (always latest release). 

Something has changed recently that caused issue [#141](https://github.com/dgraziotin/docker-nginx-webdav-nononsense/issues/141).

`s6-supervise nginx: warning: unable to spawn ./run (waiting 60 seconds): Permission denied`

I picked version `jammy-572c3250-ls108` as base image and the issue is not there anymore.

[Comparing](https://github.com/linuxserver/docker-baseimage-ubuntu/compare/jammy-572c3250-ls108...jammy-d38c1004-ls113 ) `jammy-572c3250-ls108` to the latest release `jammy-d38c1004-ls113`) does not show anything odd in particular.

Has anything changed recently that requires me to make changes? 

### Steps To Reproduce

Clone https://github.com/dgraziotin/docker-nginx-webdav-nononsense

Run it

### Environment

```markdown
- OS:
- How docker service was installed:
```

### Docker creation

```bash
https://github.com/dgraziotin/docker-nginx-webdav-nononsense/blob/main/Dockerfile docker compose build?
```

### Container logs

```bash
✔ Container nginxwebdav  Recreated                                                                                                                                                                                                    0.0s 
Attaching to nginxwebdav
nginxwebdav  | [migrations] started
nginxwebdav  | [migrations] no migrations found
nginxwebdav  | Linking /config/nginx/http.conf to /etc/nginx/conf.d/
nginxwebdav  | Linking /config/nginx/server.conf to /etc/nginx/conf.d/
nginxwebdav  | Linking /config/nginx/location.conf to /etc/nginx/conf.d/
nginxwebdav  | Linking /config/nginx/htpasswd to /etc/nginx/htpasswd
nginxwebdav  | ───────────────────────────────────────
nginxwebdav  |   _____ __ __ _____ _____ _____ _____ 
nginxwebdav  |  |     |  |  |   __|_   _|     |     |
nginxwebdav  |  |   --|  |  |__   | | | |  |  | | | |
nginxwebdav  |  |_____|_____|_____| |_| |_____|_|_|_|
nginxwebdav  |        _____ __ __ _ __    ____  
nginxwebdav  |       | __  |  |  | |  |  |    \ 
nginxwebdav  |       | __ -|  |  | |  |__|  |  |
nginxwebdav  |       |_____|_____|_|_____|____/ 
nginxwebdav  | 
nginxwebdav  |   Based on images from linuxserver.io
nginxwebdav  | ───────────────────────────────────────
nginxwebdav  | 
nginxwebdav  | To support LSIO projects visit:
nginxwebdav  | https://www.linuxserver.io/donate/
nginxwebdav  | 
nginxwebdav  | ───────────────────────────────────────
nginxwebdav  | GID/UID
nginxwebdav  | ───────────────────────────────────────
nginxwebdav  | 
nginxwebdav  | User UID:    501
nginxwebdav  | User GID:    20
nginxwebdav  | ───────────────────────────────────────
nginxwebdav  | 
nginxwebdav  | [custom-init] No custom files found, skipping...
nginxwebdav  | s6-supervise nginx: warning: unable to spawn ./run (waiting 60 seconds): Permission denied
nginxwebdav  | [ls.io-init] done.
nginxwebdav  | s6-supervise nginx: warning: unable to spawn ./run (waiting 60 seconds): Permission denied
```
```

**Comment by Roxedus** [comment]
No regression. We removed deprecated logic for S6V2 handling, this includes logic for adding the execute bit on `/etc/cont-init.d/*` and ` /etc/services.d/*`, you should make these files executable in your repo.

Also consider using the V3 syntax. <https://www.linuxserver.io/blog/how-is-container-formed> is the documentation and support we give.

**Comment by dgraziotin** [comment]
Thank you, I will adapt to the new system!
