### ISSUE TITLE
Consider including vi

### ISSUE THREAD

**Issue by ironicbadger** [linuxserver/docker-baseimage-xenial#41]
Focal Fossa image doesn't ship with vi which is very handy for troubleshooting purposes. Please consider adding it.

**Comment by aptalca** [comment]
We didn't yet release the focal image (due to outstanding bugs), but we'll consider adding that.

Thanks

PS. In the meantime, you can add it with https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

**Comment by thelamer** [comment]
Basically the first thing I do when debugging is `apk add vim` or `apt-get update && apt-get install vim` so I see the value in it, no doubt. 
I just think as a base image we should not be bundling anything unless it is something many downstream images need, ie gnupg bulked the size, but almost all ubuntu images need it to add repos , we do bash but we use bash in our init logic, we do curl and basically everything uses that. 
I cannot come up with a similar value proposition for vi/vim/nano/emacs outside of a convenience thing for a smaller subset of users.

**Comment by ironicbadger** [comment]
may as well close
