### ISSUE TITLE
Custom scripts permission issues

### ISSUE THREAD

**Issue by yurinnick** [linuxserver/docker-baseimage-xenial#75]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Container can start with `/config` mounted to NFS with permissions restricted to a certain user:  `root_squash`

## Current Behavior
`chown -R 0:0 /config/{custom-cont-init.d,custom-services.d}` fails due to lack of permissions

## Steps to Reproduce
1. Configure NFS mount with `root_squash` and map NFS root user to `1001:1000` user/group (matches `abc:abc`)
2. Start a container, in my case: `ghcr.io/linuxserver/qbittorrent:latest`
3. Check log files

## Environment
**OS:** k3os
**CPU architecture:** x86_64
**How docker service was installed:** containerd

## Docker logs
```
Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1001
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
chown: changing ownership of '/config/custom-cont-init.d': Operation not permitted
chown: changing ownership of '/config/custom-services.d': Operation not permitted
[cont-init.d] 90-custom-folders: exited 1.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by yurinnick** [comment]
Why not chown those directories as `abc:abc`? Are there any security implications for it?

**Comment by Roxedus** [comment]
Yes. When owned by abc, any vulnerable downstream application could gain root access, as the scripts in these folders are run as root.

**Comment by yurinnick** [comment]
Any workaround recommendation? Can we have `THIS_IS_UNSECURE_BUT_I_KNOW_WHAT_I AM_DOING` flag?

**Comment by aptalca** [comment]
This is the file responsible: https://github.com/linuxserver/docker-baseimage-ubuntu/blob/bionic/root/etc/cont-init.d/90-custom-folders
You can map a custom one there in all of our containers and that will act as that flag, with the confirmation that you do know what you're doing
