### ISSUE TITLE
upgrade to coreutils 9.0 for nfs 4.2 server-side-copy support

### ISSUE THREAD

**Issue by craftyguy** [linuxserver/docker-baseimage-xenial#91]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
When a container does a copy/mv on an NFS mount from a server running NFS 4.2, server-side copy should be used.

## Current Behavior
Using the sonarr container (for example) with an nfs mount, when it copies files (often several GB in size), it copies them into memory on the client and then writes them back to the nfs storage. NFS 4.2 supports server-side copy, in which the nfs server does the entire copy locally. This is *much* faster.

Current coreutils in the container baseimage is 8.3, which does not support this NFS 4.2 feature:

```
# cp --version
cp (GNU coreutils) 8.30
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

Also see: https://github.com/coreutils/coreutils/commit/4b04a0c3b792d27909670a81d21f2a3b3e0ea563

## Alternatives Considered

I guess I could use some other container with a base that has a newer coreutils, but I like the linuxserver.io containers :)

**Comment by Roxedus** [comment]
We don't control the version packed by Ubuntu. For this use case i suppose the alpine base on the sonarr nightly doesn't help either, as that's probably busybox's version. 

Are you sure sonarr uses the literal CP utility for it's operations?

**Comment by craftyguy** [comment]
> For this use case i suppose the alpine base on the sonarr nightly doesn't help either, as that's probably busybox's version.

Correct, unless they explicitly install the `coreutils` package in Alpine, it'll only have the busybox `cp`.

> Are you sure sonarr uses the literal CP utility for it's operations?

I'm not, I'll try to look into it..

**Comment by craftyguy** [comment]
I should add, I used to run sonarr "natively" on the system (with an Arch Linux host OS), and moved to using this container, and saw a massive reduction in copy performance (from ~50MB/s over NFS to like around 1MB/s). It seems very likely it is because of it using the older coreutils, since there were no other changes to the hardware or NFS server. But I'll try to figure out how sonarr does a file copy.

**Comment by nemchik** [comment]
Another thing to be mindful of is volumes. If you have a separate volume for downloads and media (sonarr root folder) transfers will happen as if they were copy-then-delete. If you have a single volume for downloads and media and on the host side that's on a single disk transfers will happen as if they were just move from one folder to another (atomic moves).

**Comment by craftyguy** [comment]
@nemchik ah, I currently have two separate volumes in the container for downloads and media, but physically they both reside on the same NFS share. so what you're saying is I should have just one volume in the container that points to the NFS share ?

**Comment by nemchik** [comment]
That would likely improve speeds, yes. I do /storage inside the container and then I have /storage/downloads and /storage/media

**Comment by craftyguy** [comment]
@nemchik thanks for the suggestion, that definitely helped
